# Site settings
title: ProdBlog
email: rob@prodblog.xyz
description: > # this means to ignore newlines until "baseurl:"
  ProdBlog is a blog by Robert Merki about product development, books, rants, and entrepreneurship.
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /:categories/:title
url: "http://www.prodblog.xyz" # the base hostname & protocol for your site
twitter_username: robmerki
github_username:  robmerki

# Build settings
markdown: kramdown
highlighter: pygments
excerpt_separator: <!--more-->
