# Site settings
title: Robert Merki's Blog
email: rob@merki.ca
description: > # this means to ignore newlines until "baseurl:"
  This is the blog of Robert Merki. I will be writing about powerlifting,
  building products, Ruby on Rails, personal development, and entrepreneurship.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://merki.ca" # the base hostname & protocol for your site
twitter_username: robmerki
github_username:  robmerki

# Build settings
markdown: kramdown
highlighter: pygments
excerpt_separator: <!--more-->
